//! The thin `cqrs-es` adapter over the pure `DnaTest` decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Like Event, `DnaTest` has a cross-aggregate
//! reference (the anchoring Person), so its `Services` is an [`Arc<dyn DnaTestRefResolver>`].

use std::sync::Arc;

use crate::dna_test::command::DnaTestCommandEnvelope;
use crate::dna_test::error::DnaTestError;
use crate::dna_test::event::DnaTestEvent;
use crate::dna_test::ref_resolver::DnaTestRefResolver;
use crate::dna_test::state::DnaTestState;

crate::cqrs_adapter! {
    state: DnaTestState,
    type: "dna_test",
    command: DnaTestCommandEnvelope,
    event: DnaTestEvent,
    error: DnaTestError,
    services: Arc<dyn DnaTestRefResolver>,
    decide: crate::dna_test::decide::decide,
    evolve: crate::dna_test::decide::evolve,
}
