//! Identifier newtypes for aggregates and assertions.
//!
//! Aggregate ids and the [`AssertionId`] are **UUID v7** (time-sortable — ADR 0004 §5);
//! [`HumanId`] is the user-facing identifier (the Gramps `gramps_id` analog — data-model §7).
//!
//! UUIDs are *generated by the application layer* and passed into the domain core; nothing
//! here samples a clock or random source, keeping the decision core pure (ADR 0004 §3).

use std::fmt;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Declares a UUID-v7 newtype with the standard derives, `Display`, and `Uuid` conversions.
macro_rules! uuid_newtype {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize,
        )]
        pub struct $name(Uuid);

        impl $name {
            /// Wraps an already-generated UUID v7 (produced by the application layer).
            #[must_use]
            pub const fn from_uuid(id: Uuid) -> Self {
                Self(id)
            }

            /// Returns the wrapped UUID.
            #[must_use]
            pub const fn as_uuid(&self) -> Uuid {
                self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl From<Uuid> for $name {
            fn from(id: Uuid) -> Self {
                Self(id)
            }
        }
    };
}

uuid_newtype!(
    /// Identity of a `Person` aggregate.
    PersonId
);
uuid_newtype!(
    /// Identity of a `Family` aggregate.
    FamilyId
);
uuid_newtype!(
    /// Identity of an `Event` aggregate.
    EventId
);
uuid_newtype!(
    /// Identity of a `Place` aggregate.
    PlaceId
);
uuid_newtype!(
    /// Identity of a `Source` aggregate.
    SourceId
);
uuid_newtype!(
    /// Identity of a `Citation` aggregate.
    CitationId
);
uuid_newtype!(
    /// Identity of a `Repository` aggregate.
    RepositoryId
);
uuid_newtype!(
    /// Identity of a `Media` aggregate.
    MediaId
);
uuid_newtype!(
    /// Identity of a `Note` aggregate.
    NoteId
);
uuid_newtype!(
    /// Identity of a `Tag` aggregate.
    TagId
);
uuid_newtype!(
    /// Identity of a `DnaTest` aggregate.
    DnaTestId
);
uuid_newtype!(
    /// Identity of a `DnaMatch` aggregate.
    DnaMatchId
);
uuid_newtype!(
    /// Identity of a `ResearchNote` aggregate (ADR 0028).
    ResearchNoteId
);
uuid_newtype!(
    /// Identity of a single assertion (one event), carried in the payload so a correction
    /// can target it portably (ADR 0004 §2).
    AssertionId
);
uuid_newtype!(
    /// Identity of an [`crate::provenance::Agent`] (the operator of an event).
    AgentId
);

/// The user-facing identifier (the Gramps `gramps_id` analog — data-model §7).
///
/// Distinct from the aggregate id (a UUID v7): a `HumanId` is a short, human-readable label
/// such as `I0042`, assigned by the application, not the storage key.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct HumanId(String);

impl HumanId {
    /// Wraps a user-facing identifier string.
    #[must_use]
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Returns the identifier as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for HumanId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::{HumanId, PersonId};
    use uuid::Uuid;

    #[test]
    fn person_id_round_trips_through_json() {
        let id = PersonId::from_uuid(Uuid::from_u128(0x0190_0000_0000_7000_8000_0000_0000_0001));
        let json = serde_json::to_string(&id).unwrap();
        let back: PersonId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, back);
    }

    #[test]
    fn person_id_displays_as_uuid() {
        let uuid = Uuid::from_u128(0x0190_0000_0000_7000_8000_0000_0000_0001);
        let id = PersonId::from_uuid(uuid);
        assert_eq!(id.to_string(), uuid.to_string());
        assert_eq!(id.as_uuid(), uuid);
    }

    #[test]
    fn human_id_preserves_its_string() {
        let id = HumanId::new("I0042");
        assert_eq!(id.as_str(), "I0042");
        assert_eq!(id.to_string(), "I0042");
    }
}
