//! The thin `cqrs-es` adapter over the pure Event decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Like Citation, Event has a cross-aggregate
//! reference, so its `Services` is an [`Arc<dyn EventRefResolver>`]: `handle` resolves the
//! cross-aggregate facts (does the linked place exist?) through that resolver — the aggregate-tax
//! read of ADR 0004 §3 — then passes the resolved
//! [`EventRefs`](crate::event::ref_resolver::EventRefs) into the pure `decide`.

use std::sync::Arc;

use crate::event::command::EventCommandEnvelope;
use crate::event::error::EventError;
use crate::event::events::EventEvent;
use crate::event::ref_resolver::EventRefResolver;
use crate::event::state::EventState;

crate::cqrs_adapter! {
    state: EventState,
    type: "event",
    command: EventCommandEnvelope,
    event: EventEvent,
    error: EventError,
    services: Arc<dyn EventRefResolver>,
    decide: crate::event::decide::decide,
    evolve: crate::event::decide::evolve,
}
