[package]
name = "vitni-gramps-xml"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vitni-interchange = { workspace = true }
thiserror = { workspace = true }
quick-xml = { workspace = true }
flate2 = { workspace = true }

[lints]
workspace = true
