//! The thin `cqrs-es` adapter over the pure Source decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Like Citation, Source has a cross-aggregate
//! reference (the repositories it links), so its `Services` is an [`Arc<dyn SourceRefResolver>`]:
//! `handle` resolves whether the linked repository exists — the aggregate-tax read of ADR 0004 §3 —
//! then passes the resolved [`SourceRefs`](crate::source::ref_resolver::SourceRefs) into `decide`.

use std::sync::Arc;

use crate::source::command::SourceCommandEnvelope;
use crate::source::error::SourceError;
use crate::source::event::SourceEvent;
use crate::source::ref_resolver::SourceRefResolver;
use crate::source::state::SourceState;

crate::cqrs_adapter! {
    state: SourceState,
    type: "source",
    command: SourceCommandEnvelope,
    event: SourceEvent,
    error: SourceError,
    services: Arc<dyn SourceRefResolver>,
    decide: crate::source::decide::decide,
    evolve: crate::source::decide::evolve,
}
