//! The thin `cqrs-es` adapter over the pure Source decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Source has no cross-aggregate reference, so
//! its `Services` is `()` (contrast the Citation aggregate, whose `Services` resolves the
//! `UnknownSource` check — ADR 0004 §3).

use crate::source::command::SourceCommandEnvelope;
use crate::source::error::SourceError;
use crate::source::event::SourceEvent;
use crate::source::state::SourceState;

crate::cqrs_adapter! {
    state: SourceState,
    type: "source",
    command: SourceCommandEnvelope,
    event: SourceEvent,
    error: SourceError,
    decide: crate::source::decide::decide,
    evolve: crate::source::decide::evolve,
}
