//! The thin `cqrs-es` adapter over the pure Repository decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Repository has no cross-aggregate reference,
//! so its `Services` is `()`.

use crate::repository::command::RepositoryCommandEnvelope;
use crate::repository::error::RepositoryError;
use crate::repository::event::RepositoryEvent;
use crate::repository::state::RepositoryState;

crate::cqrs_adapter! {
    state: RepositoryState,
    type: "repository",
    command: RepositoryCommandEnvelope,
    event: RepositoryEvent,
    error: RepositoryError,
    decide: crate::repository::decide::decide,
    evolve: crate::repository::decide::evolve,
}
