//! The thin `cqrs-es` adapter over the pure Tag decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Tag has no cross-aggregate reference, so its
//! `Services` is `()`.

use crate::tag::command::TagCommandEnvelope;
use crate::tag::error::TagError;
use crate::tag::event::TagEvent;
use crate::tag::state::TagState;

crate::cqrs_adapter! {
    state: TagState,
    type: "tag",
    command: TagCommandEnvelope,
    event: TagEvent,
    error: TagError,
    decide: crate::tag::decide::decide,
    evolve: crate::tag::decide::evolve,
}
