//! The thin `cqrs-es` adapter over the pure `DnaMatch` decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). `DnaMatch` references two `DnaTest`s, so its
//! `Services` is an [`Arc<dyn DnaMatchRefResolver>`] resolving both before `decide`.

use std::sync::Arc;

use crate::dna_match::command::DnaMatchCommandEnvelope;
use crate::dna_match::error::DnaMatchError;
use crate::dna_match::event::DnaMatchEvent;
use crate::dna_match::ref_resolver::DnaMatchRefResolver;
use crate::dna_match::state::DnaMatchState;

crate::cqrs_adapter! {
    state: DnaMatchState,
    type: "dna_match",
    command: DnaMatchCommandEnvelope,
    event: DnaMatchEvent,
    error: DnaMatchError,
    services: Arc<dyn DnaMatchRefResolver>,
    decide: crate::dna_match::decide::decide,
    evolve: crate::dna_match::decide::evolve,
}
