[package]
name = "vitni-i18n"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
i18n-embed = { workspace = true }
tracing = { workspace = true }
unic-langid = { workspace = true }

[lints]
workspace = true
