//! The thin `cqrs-es` adapter over the pure Media decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Media has no cross-aggregate reference, so
//! its `Services` is `()`.

use crate::media::command::MediaCommandEnvelope;
use crate::media::error::MediaError;
use crate::media::event::MediaEvent;
use crate::media::state::MediaState;

crate::cqrs_adapter! {
    state: MediaState,
    type: "media",
    command: MediaCommandEnvelope,
    event: MediaEvent,
    error: MediaError,
    decide: crate::media::decide::decide,
    evolve: crate::media::decide::evolve,
}
