//! The thin `cqrs-es` adapter over the pure `ImportRun` decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). A run references no other aggregate, so its
//! `Services` is `()`.

use crate::import_run::command::ImportRunCommandEnvelope;
use crate::import_run::error::ImportRunError;
use crate::import_run::event::ImportRunEvent;
use crate::import_run::state::ImportRunState;

crate::cqrs_adapter! {
    state: ImportRunState,
    type: "import_run",
    command: ImportRunCommandEnvelope,
    event: ImportRunEvent,
    error: ImportRunError,
    decide: crate::import_run::decide::decide,
    evolve: crate::import_run::decide::evolve,
}
