//! Duplicate-person detection (Phase 5 PR 19): a typed finding over the Person projection so the
//! Compare/merge screen's "possible duplicates" table — and, later, the dashboard's own duplicates
//! check (`docs/archive/phase5/plan.md`, "Possible duplicates overlaps PR19") — can reuse the same scan.
//!
//! This is a pure, in-memory heuristic over already-projected [`PersonSummary`]s: no new events, no
//! extra I/O beyond [`list_persons`]. It flags two kinds of pairs (data, not display strings — the
//! frontend localizes [`MatchKind`], keeping this crate string-free per ADR 0003):
//! - [`MatchKind::NameVariant`] — same normalized surname, given names close but not identical
//!   (e.g. "Smith"/"Smyth" surname typo, or "Jon"/"Jonathan" given-name variants).
//! - [`MatchKind::SameBirthYear`] — identical normalized name, birth years within
//!   [`BIRTH_YEAR_WINDOW`] of each other.
//!
//! Sub-quadratic over persons: rather than comparing every unordered pair, candidate pairs are
//! generated by a *deletion-neighbourhood* (`SymSpell`) index — every normalized name is hashed to the
//! set of strings reachable by deleting up to [`NAME_VARIANT_MAX_DISTANCE`] characters, and two names
//! collide in that index whenever their Levenshtein distance is within that bound (identical names
//! collide at the zero-deletion variant). Only colliding pairs are then run through the exact
//! [`compare`] check, so the result is identical to a brute-force all-pairs scan while touching a
//! small fraction of the pairs. A dependency-free Levenshtein distance drives the "close but not
//! identical" name check rather than pulling in a string-similarity crate for one small comparison.

use std::collections::{HashMap, HashSet};

use crate::dto::AggRef;
use crate::error::AppError;
use crate::person::{PersonSummary, list_persons};
use crate::workspace::Workspace;

/// How many years apart two identically-named persons' birth years may be and still count as
/// [`MatchKind::SameBirthYear`] (inclusive).
const BIRTH_YEAR_WINDOW: i32 = 3;

/// The maximum Levenshtein distance between two normalized given or surname strings that still
/// counts as a "variant" of each other for [`MatchKind::NameVariant`].
const NAME_VARIANT_MAX_DISTANCE: usize = 2;

/// Why a pair of persons was flagged as a possible duplicate — a small closed enum the frontend
/// localizes to its own display text (ADR 0003 keeps this crate string-free).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MatchKind {
    /// The names are close but not identical (a likely transcription/spelling variant).
    NameVariant,
    /// The (normalized) names are identical and the birth years are close.
    SameBirthYear,
}

/// A candidate duplicate pair: two persons, why they were flagged, and a rough confidence score.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DuplicateCandidate {
    /// The first person in the pair.
    pub a: AggRef,
    /// The second person in the pair.
    pub b: AggRef,
    /// Why the pair was flagged.
    pub kind: MatchKind,
    /// A rough confidence score in `0..=100` (higher = more likely a true duplicate). Not a
    /// [`genealogy_core::provenance::Confidence`] — this is a heuristic match score, not an
    /// operator's asserted surety.
    pub score: u8,
}

/// Scans every likely-duplicate pair of persons in the workspace for possible duplicates.
///
/// Returns an empty vector for a workspace with fewer than two persons. Pairs with clearly distinct
/// names and clearly distinct (or unknown) birth years are never flagged. Loads the person
/// projection once, then delegates to [`scan_duplicates`].
///
/// # Errors
///
/// A store/read-model error from the underlying [`list_persons`] scan.
pub async fn find_duplicate_candidates(workspace: &Workspace) -> Result<Vec<DuplicateCandidate>, AppError> {
    let persons = list_persons(workspace).await?;
    Ok(scan_duplicates(&persons))
}

/// Scans an already-loaded person projection for possible-duplicate pairs.
///
/// Pure and I/O-free so the dashboard's data-quality pass can share a single [`list_persons`] load
/// with the other checks. Candidate pairs come from the deletion-neighbourhood index
/// ([`candidate_pairs`]); each is confirmed by the exact [`compare`] check, yielding the same set a
/// brute-force all-pairs scan would (verified by the `bucketed_scan_matches_brute_force` test).
#[must_use]
pub(crate) fn scan_duplicates(persons: &[PersonSummary]) -> Vec<DuplicateCandidate> {
    let names: Vec<Option<String>> = persons.iter().map(normalized_name).collect();
    let mut candidates = Vec::new();
    for (i, j) in candidate_pairs(&names) {
        let (Some(name_a), Some(name_b)) = (&names[i], &names[j]) else {
            continue;
        };
        if let Some(candidate) = compare(&persons[i], &persons[j], name_a, name_b) {
            candidates.push(candidate);
        }
    }
    candidates
}

/// The ascending-ordered `(i, j)` (with `i < j`) index pairs worth running through [`compare`].
///
/// Buckets every named person by each string reachable from its normalized name via up to
/// [`NAME_VARIANT_MAX_DISTANCE`] single-character deletions (the `SymSpell` deletion neighbourhood).
/// Two names whose Levenshtein distance is within that bound always share at least one such string
/// (identical names share their zero-deletion variant), so every pair a brute-force scan could flag
/// appears in some bucket. Pairs are de-duplicated and sorted so the output order matches the
/// brute-force nested-loop order exactly.
fn candidate_pairs(names: &[Option<String>]) -> Vec<(usize, usize)> {
    let mut buckets: HashMap<String, Vec<usize>> = HashMap::new();
    for (index, name) in names.iter().enumerate() {
        let Some(name) = name else {
            continue;
        };
        for variant in deletion_variants(name, NAME_VARIANT_MAX_DISTANCE) {
            buckets.entry(variant).or_default().push(index);
        }
    }
    let mut pairs: HashSet<(usize, usize)> = HashSet::new();
    for bucket in buckets.values() {
        add_bucket_pairs(bucket, &mut pairs);
    }
    let mut pairs: Vec<(usize, usize)> = pairs.into_iter().collect();
    pairs.sort_unstable();
    pairs
}

/// Adds every unordered pair drawn from `bucket` (as `(min, max)` index tuples) to `pairs`.
fn add_bucket_pairs(bucket: &[usize], pairs: &mut HashSet<(usize, usize)>) {
    for a in 0..bucket.len() {
        for b in (a + 1)..bucket.len() {
            let (i, j) = (bucket[a], bucket[b]);
            pairs.insert((i.min(j), i.max(j)));
        }
    }
}

/// Every distinct string reachable from `name` by deleting up to `max_deletions` characters,
/// including `name` itself (zero deletions).
///
/// This is the `SymSpell` deletion neighbourhood: for a maximum edit distance of `max_deletions`, two
/// strings within that Levenshtein distance are guaranteed to share at least one member of each
/// other's neighbourhood, which is what lets [`candidate_pairs`] bucket without missing a pair.
fn deletion_variants(name: &str, max_deletions: usize) -> HashSet<String> {
    let mut variants: HashSet<String> = HashSet::new();
    variants.insert(name.to_owned());
    let mut frontier: HashSet<Vec<char>> = HashSet::new();
    frontier.insert(name.chars().collect());
    for _ in 0..max_deletions {
        let mut next: HashSet<Vec<char>> = HashSet::new();
        for sequence in &frontier {
            for drop_at in 0..sequence.len() {
                let mut shortened = sequence.clone();
                shortened.remove(drop_at);
                variants.insert(shortened.iter().collect());
                next.insert(shortened);
            }
        }
        frontier = next;
    }
    variants
}

/// Compares two persons whose normalized names are already computed, returning a
/// [`DuplicateCandidate`] if either heuristic fires.
///
/// Checked in order: an identical normalized name with close birth years fires
/// [`MatchKind::SameBirthYear`] first (the stronger signal); otherwise a close-but-not-identical name
/// fires [`MatchKind::NameVariant`]. `name_a`/`name_b` are the precomputed [`normalized_name`]s of
/// `a`/`b`, passed in so the bucketed scan normalizes each name once.
fn compare(a: &PersonSummary, b: &PersonSummary, name_a: &str, name_b: &str) -> Option<DuplicateCandidate> {
    let birth_a = a.birth_year();
    let birth_b = b.birth_year();

    if name_a == name_b {
        let (Some(year_a), Some(year_b)) = (birth_a, birth_b) else {
            return None;
        };
        if (year_a - year_b).abs() <= BIRTH_YEAR_WINDOW {
            let score = same_birth_year_score(year_a, year_b);
            return Some(candidate(a, b, MatchKind::SameBirthYear, score));
        }
        return None;
    }

    let distance = levenshtein(name_a, name_b);
    if (1..=NAME_VARIANT_MAX_DISTANCE).contains(&distance) {
        let score = name_variant_score(distance);
        return Some(candidate(a, b, MatchKind::NameVariant, score));
    }
    None
}

/// Builds the [`DuplicateCandidate`] DTO for a flagged pair.
fn candidate(a: &PersonSummary, b: &PersonSummary, kind: MatchKind, score: u8) -> DuplicateCandidate {
    DuplicateCandidate {
        a: AggRef {
            human_id: a.human_id.clone(),
            id: a.human_id.clone(),
        },
        b: AggRef {
            human_id: b.human_id.clone(),
            id: b.human_id.clone(),
        },
        kind,
        score,
    }
}

/// The case/whitespace-normalized "given surname" display name, or `None` if the person has none.
fn normalized_name(summary: &PersonSummary) -> Option<String> {
    let name = summary.display_name.as_ref()?;
    let normalized = name.split_whitespace().collect::<Vec<_>>().join(" ").to_lowercase();
    (!normalized.is_empty()).then_some(normalized)
}

/// A rough confidence score for a same-name, close-birth-year match: highest for an exact year
/// match, decreasing with the gap.
fn same_birth_year_score(year_a: i32, year_b: i32) -> u8 {
    let gap = (year_a - year_b).unsigned_abs();
    let penalty = u8::try_from(gap.saturating_mul(10)).unwrap_or(u8::MAX);
    95_u8.saturating_sub(penalty)
}

/// A rough confidence score for a name-variant match: highest for a 1-character difference,
/// decreasing with the edit distance.
fn name_variant_score(distance: usize) -> u8 {
    let penalty = u8::try_from(distance.saturating_mul(20)).unwrap_or(u8::MAX);
    80_u8.saturating_sub(penalty)
}

/// The Levenshtein (edit) distance between two strings, hand-rolled to avoid pulling in a
/// string-similarity crate for this one heuristic (`~O(len_a * len_b)`, fine for short names).
fn levenshtein(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    let mut previous_row: Vec<usize> = (0..=b.len()).collect();
    let mut current_row = vec![0_usize; b.len() + 1];

    for (i, &char_a) in a.iter().enumerate() {
        current_row[0] = i + 1;
        for (j, &char_b) in b.iter().enumerate() {
            let cost = usize::from(char_a != char_b);
            current_row[j + 1] = (previous_row[j] + cost)
                .min(previous_row[j + 1] + 1)
                .min(current_row[j] + 1);
        }
        std::mem::swap(&mut previous_row, &mut current_row);
    }
    previous_row[b.len()]
}

#[cfg(test)]
mod tests {
    use super::{
        DuplicateCandidate, MatchKind, compare, find_duplicate_candidates, levenshtein, normalized_name,
        scan_duplicates,
    };
    use crate::config::{AppDefaults, IdFormats, OperatorConfig, WorkspaceDefaults};
    use crate::event::{DateParts, NewEvent, assert_event_date, create_event};
    use crate::person::{
        NewParticipation, NewPerson, PersonNameParts, PersonSummary, assert_participation, create_person, list_persons,
    };
    use crate::session::Session;
    use crate::use_case::{MutationMeta, Provenance};
    use crate::workspace::Workspace;
    use genealogy_core::enums::{EventType, EvidenceLevel, ParticipantRole};
    use genealogy_core::ids::AgentId;
    use genealogy_core::provenance::{Agent, AgentKind, Confidence};
    use tempfile::TempDir;
    use uuid::Uuid;

    fn operator() -> OperatorConfig {
        OperatorConfig {
            id: AgentId::from_uuid(Uuid::from_u128(1)),
            display: Some("Ada".to_owned()),
            email: None,
        }
    }

    fn defaults() -> WorkspaceDefaults {
        WorkspaceDefaults {
            id_formats: IdFormats {
                person: "I%04d".to_owned(),
                ..IdFormats::default()
            },
            ..Default::default()
        }
    }

    fn session() -> Session {
        Session::new(Agent {
            kind: AgentKind::Human,
            id: AgentId::from_uuid(Uuid::from_u128(1)),
            display: Some("Ada".to_owned()),
        })
    }

    async fn setup() -> (Workspace, Session, TempDir) {
        let dir = tempfile::tempdir().expect("tempdir");
        let ws = dir.path().join("ws");
        Workspace::init(&ws, &operator(), &AppDefaults::default(), None).expect("init");
        let workspace = Workspace::open(&ws, &operator(), &defaults()).await.expect("open");
        (workspace, session(), dir)
    }

    async fn person(workspace: &Workspace, session: &Session, given: &str, surname: &str) -> String {
        create_person(
            workspace,
            session,
            NewPerson {
                human_id: None,
                name: Some(PersonNameParts::simple(
                    Some(given.to_owned()),
                    Some(surname.to_owned()),
                )),
                evidence_level: EvidenceLevel::Conclusion,
            },
            Provenance::default(),
            &[],
        )
        .await
        .expect("create person")
    }

    /// Asserts a dated Birth event with the person as its Primary participant — the promoted shape
    /// vital claims take (ADR 0021 §2), so the duplicate scan reads birth years from events.
    async fn with_birth_year(workspace: &Workspace, session: &Session, human_id: &str, year: i32) {
        let event_id = create_event(
            workspace,
            session,
            NewEvent {
                human_id: None,
                event_type: EventType::Birth,
            },
            Provenance::default(),
            &[],
        )
        .await
        .expect("create birth event");
        assert_event_date(
            workspace,
            session,
            &event_id,
            DateParts {
                year,
                month: None,
                day: None,
            },
            MutationMeta {
                provenance: Provenance::default(),
                citations: &[],
                supersedes: None,
            },
        )
        .await
        .expect("assert event date");
        assert_participation(
            workspace,
            session,
            human_id,
            &event_id,
            NewParticipation::with_role(ParticipantRole::Primary),
            MutationMeta {
                provenance: Provenance {
                    confidence: Some(Confidence::Normal),
                    rationale: None,
                    evidence_analysis: None,
                },
                citations: &[],
                supersedes: None,
            },
        )
        .await
        .expect("assert participation");
    }

    #[test]
    fn levenshtein_counts_single_character_edits() {
        assert_eq!(levenshtein("smith", "smith"), 0);
        assert_eq!(levenshtein("smith", "smyth"), 1);
        assert_eq!(levenshtein("kitten", "sitting"), 3);
    }

    #[tokio::test]
    async fn empty_workspace_returns_no_candidates() {
        let (workspace, _session, _dir) = setup().await;
        let candidates = find_duplicate_candidates(&workspace).await.expect("scan");
        assert!(candidates.is_empty());
    }

    #[tokio::test]
    async fn flags_a_name_variant_pair() {
        let (workspace, session, _dir) = setup().await;
        let a = person(&workspace, &session, "John", "Smith").await;
        let b = person(&workspace, &session, "John", "Smyth").await;

        let candidates = find_duplicate_candidates(&workspace).await.expect("scan");
        let pair = candidates
            .iter()
            .find(|c| (c.a.human_id == a && c.b.human_id == b) || (c.a.human_id == b && c.b.human_id == a))
            .expect("name-variant pair flagged");
        assert_eq!(pair.kind, MatchKind::NameVariant);
    }

    #[tokio::test]
    async fn flags_a_same_birth_year_pair() {
        let (workspace, session, _dir) = setup().await;
        let a = person(&workspace, &session, "Mary", "Doe").await;
        let b = person(&workspace, &session, "Mary", "Doe").await;
        with_birth_year(&workspace, &session, &a, 1900).await;
        with_birth_year(&workspace, &session, &b, 1902).await;

        let candidates = find_duplicate_candidates(&workspace).await.expect("scan");
        let pair = candidates
            .iter()
            .find(|c| (c.a.human_id == a && c.b.human_id == b) || (c.a.human_id == b && c.b.human_id == a))
            .expect("same-birth-year pair flagged");
        assert_eq!(pair.kind, MatchKind::SameBirthYear);
    }

    #[tokio::test]
    async fn does_not_flag_clearly_distinct_persons() {
        let (workspace, session, _dir) = setup().await;
        let a = person(&workspace, &session, "Alice", "Anderson").await;
        let b = person(&workspace, &session, "Bob", "Baker").await;
        with_birth_year(&workspace, &session, &a, 1900).await;
        with_birth_year(&workspace, &session, &b, 1980).await;

        let candidates = find_duplicate_candidates(&workspace).await.expect("scan");
        assert!(
            candidates
                .iter()
                .all(|c| { !((c.a.human_id == a && c.b.human_id == b) || (c.a.human_id == b && c.b.human_id == a)) }),
            "clearly distinct persons must not be flagged: {candidates:?}"
        );
    }

    /// The brute-force all-pairs oracle: the original O(n²) scan, kept in the test module so the
    /// bucketed [`scan_duplicates`] can be proven to produce the identical result.
    fn brute_force(persons: &[PersonSummary]) -> Vec<DuplicateCandidate> {
        let names: Vec<Option<String>> = persons.iter().map(normalized_name).collect();
        let mut candidates = Vec::new();
        for i in 0..persons.len() {
            for j in (i + 1)..persons.len() {
                let (Some(name_a), Some(name_b)) = (&names[i], &names[j]) else {
                    continue;
                };
                if let Some(candidate) = compare(&persons[i], &persons[j], name_a, name_b) {
                    candidates.push(candidate);
                }
            }
        }
        candidates
    }

    /// Proves the bucketed [`scan_duplicates`] returns exactly what the brute-force oracle does over a
    /// fixture spanning every branch: identical names with close/far birth years, one- and two-edit
    /// name variants (including a cross-surname typo the naive "same surname" bucket would miss), a
    /// distance-3 non-match, short names that collide only at the empty-string variant, and an
    /// unnamed person the scan must skip.
    #[tokio::test]
    async fn bucketed_scan_matches_brute_force() {
        let (workspace, session, _dir) = setup().await;
        let mary_a = person(&workspace, &session, "Mary", "Doe").await;
        let mary_b = person(&workspace, &session, "Mary", "Doe").await;
        let mary_c = person(&workspace, &session, "Mary", "Doe").await;
        with_birth_year(&workspace, &session, &mary_a, 1900).await;
        with_birth_year(&workspace, &session, &mary_b, 1902).await;
        with_birth_year(&workspace, &session, &mary_c, 1950).await;
        person(&workspace, &session, "John", "Smith").await;
        person(&workspace, &session, "John", "Smyth").await;
        person(&workspace, &session, "Katherine", "Brown").await;
        person(&workspace, &session, "Catherine", "Brown").await;
        person(&workspace, &session, "Jon", "Snow").await;
        person(&workspace, &session, "Jonn", "Snow").await;
        person(&workspace, &session, "Alice", "Anderson").await;
        person(&workspace, &session, "Bob", "Baker").await;
        person(&workspace, &session, "Al", "").await;
        person(&workspace, &session, "Bo", "").await;
        create_person(
            &workspace,
            &session,
            NewPerson {
                human_id: None,
                name: None,
                evidence_level: EvidenceLevel::Conclusion,
            },
            Provenance::default(),
            &[],
        )
        .await
        .expect("create unnamed person");

        let persons = list_persons(&workspace).await.expect("list");
        let expected = brute_force(&persons);
        let actual = scan_duplicates(&persons);

        assert!(
            !expected.is_empty(),
            "the fixture must exercise at least one flagged pair"
        );
        assert_eq!(
            actual, expected,
            "bucketed scan must match the brute-force oracle exactly"
        );
    }
}
