[package]
name = "genealogy-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["sqlite"]
sqlite = ["genealogy-db/sqlite"]
postgres = ["genealogy-db/postgres"]

[dependencies]
genealogy-core = { workspace = true }
genealogy-db = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
directories = { workspace = true }
whoami = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
