//! The thin `cqrs-es` adapter over the pure Family decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter): `handle` unpacks the command envelope, calls
//! the pure [`decide`](super::decide::decide), and writes the events; `apply` delegates to
//! [`evolve`](super::decide::evolve). Family has no cross-aggregate reference, so `Services = ()`.

use crate::family::command::FamilyCommandEnvelope;
use crate::family::error::FamilyError;
use crate::family::event::FamilyEvent;
use crate::family::state::FamilyState;

crate::cqrs_adapter! {
    state: FamilyState,
    type: "family",
    command: FamilyCommandEnvelope,
    event: FamilyEvent,
    error: FamilyError,
    decide: crate::family::decide::decide,
    evolve: crate::family::decide::evolve,
}
