//! The thin `cqrs-es` adapter over the pure Place decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Place has no cross-aggregate reference, so
//! its `Services` is `()` (contrast the Citation/Event aggregates — ADR 0004 §3).

use crate::place::command::PlaceCommandEnvelope;
use crate::place::error::PlaceError;
use crate::place::event::PlaceEvent;
use crate::place::state::PlaceState;

crate::cqrs_adapter! {
    state: PlaceState,
    type: "place",
    command: PlaceCommandEnvelope,
    event: PlaceEvent,
    error: PlaceError,
    decide: crate::place::decide::decide,
    evolve: crate::place::decide::evolve,
}
