//! The thin `cqrs-es` adapter over the pure Place decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Like Event, Place has a cross-aggregate
//! reference, so its `Services` is an [`Arc<dyn PlaceRefResolver>`]: `handle` resolves whether the
//! enclosing place exists — the aggregate-tax read of ADR 0004 §3 — then passes the resolved
//! [`PlaceRefs`](crate::place::ref_resolver::PlaceRefs) into the pure `decide`.

use std::sync::Arc;

use crate::place::command::PlaceCommandEnvelope;
use crate::place::error::PlaceError;
use crate::place::event::PlaceEvent;
use crate::place::ref_resolver::PlaceRefResolver;
use crate::place::state::PlaceState;

crate::cqrs_adapter! {
    state: PlaceState,
    type: "place",
    command: PlaceCommandEnvelope,
    event: PlaceEvent,
    error: PlaceError,
    services: Arc<dyn PlaceRefResolver>,
    decide: crate::place::decide::decide,
    evolve: crate::place::decide::evolve,
}
