//! The thin `cqrs-es` adapter over the pure Person decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter): `handle` unpacks the command envelope, calls
//! the pure [`decide`](super::decide::decide), and writes the events; `apply` delegates to
//! [`evolve`](super::decide::evolve). All business rules live in `decide`/`evolve`, keeping the door
//! open to a different store (ADR 0002). Person has no cross-aggregate reference, so `Services = ()`.

use crate::person::command::PersonCommandEnvelope;
use crate::person::error::PersonError;
use crate::person::event::PersonEvent;
use crate::person::state::PersonState;

crate::cqrs_adapter! {
    state: PersonState,
    type: "person",
    command: PersonCommandEnvelope,
    event: PersonEvent,
    error: PersonError,
    decide: crate::person::decide::decide,
    evolve: crate::person::decide::evolve,
}
