[package]
name = "vitni-digitalarkivet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
scraper = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
