//! The thin `cqrs-es` adapter over the pure Note decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Note has no cross-aggregate reference, so
//! its `Services` is `()`.

use crate::note::command::NoteCommandEnvelope;
use crate::note::error::NoteError;
use crate::note::event::NoteEvent;
use crate::note::state::NoteState;

crate::cqrs_adapter! {
    state: NoteState,
    type: "note",
    command: NoteCommandEnvelope,
    event: NoteEvent,
    error: NoteError,
    decide: crate::note::decide::decide,
    evolve: crate::note::decide::evolve,
}
