//! The thin `cqrs-es` adapter over the pure Citation decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Citation has a cross-aggregate reference, so
//! its `Services` is an [`Arc<dyn CitationRefResolver>`]: `handle` resolves the cross-aggregate
//! facts (does the cited source exist?) through that resolver — the aggregate-tax read of
//! ADR 0004 §3 — then passes the resolved
//! [`CitationRefs`](crate::citation::ref_resolver::CitationRefs) into the pure `decide`.

use std::sync::Arc;

use crate::citation::command::CitationCommandEnvelope;
use crate::citation::error::CitationError;
use crate::citation::event::CitationEvent;
use crate::citation::ref_resolver::CitationRefResolver;
use crate::citation::state::CitationState;

crate::cqrs_adapter! {
    state: CitationState,
    type: "citation",
    command: CitationCommandEnvelope,
    event: CitationEvent,
    error: CitationError,
    services: Arc<dyn CitationRefResolver>,
    decide: crate::citation::decide::decide,
    evolve: crate::citation::decide::evolve,
}
