//! The thin `cqrs-es` adapter over the pure `ResearchNote` decision core (ADR 0002, ADR 0004 §3).
//!
//! Generated by [`cqrs_adapter!`](crate::cqrs_adapter). Like Event/Citation, `ResearchNote` has a
//! cross-aggregate reference (its subject), so its `Services` is an
//! [`Arc<dyn ResearchNoteRefResolver>`]: `handle` resolves the cross-aggregate fact (does the named
//! subject exist?) through that resolver — the aggregate-tax read of ADR 0004 §3 — then passes the
//! resolved [`ResearchNoteRefs`](crate::research_note::ref_resolver::ResearchNoteRefs) into the pure
//! `decide`.

use std::sync::Arc;

use crate::research_note::command::ResearchNoteCommandEnvelope;
use crate::research_note::error::ResearchNoteError;
use crate::research_note::event::ResearchNoteEvent;
use crate::research_note::ref_resolver::ResearchNoteRefResolver;
use crate::research_note::state::ResearchNoteState;

crate::cqrs_adapter! {
    state: ResearchNoteState,
    type: "research_note",
    command: ResearchNoteCommandEnvelope,
    event: ResearchNoteEvent,
    error: ResearchNoteError,
    services: Arc<dyn ResearchNoteRefResolver>,
    decide: crate::research_note::decide::decide,
    evolve: crate::research_note::decide::evolve,
}
